export const AUDIT_ACTIONS = {
  ADMIN_USER_VIEW: "ADMIN_USER_VIEW",
  ADMIN_USER_UPDATE: "ADMIN_USER_UPDATE",
  ADMIN_USER_ROLE_CHANGE: "ADMIN_USER_ROLE_CHANGE",
  ADMIN_USER_SUSPEND: "ADMIN_USER_SUSPEND",
  ADMIN_USER_UNSUSPEND: "ADMIN_USER_UNSUSPEND",
  ADMIN_CREDIT_GRANT: "ADMIN_CREDIT_GRANT",
  ADMIN_CREDIT_DEDUCT: "ADMIN_CREDIT_DEDUCT",
  ADMIN_CREDIT_REFUND: "ADMIN_CREDIT_REFUND",
  ADMIN_JOB_VIEW: "ADMIN_JOB_VIEW",
  ADMIN_JOB_RETRY: "ADMIN_JOB_RETRY",
  ADMIN_JOB_CANCEL: "ADMIN_JOB_CANCEL",
  ADMIN_SUBSCRIPTION_VIEW: "ADMIN_SUBSCRIPTION_VIEW",
  ADMIN_PHOTOSHOOT_VIEW: "ADMIN_PHOTOSHOOT_VIEW",
  ADMIN_VIDEO_VIEW: "ADMIN_VIDEO_VIEW",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
